### ISSUE TITLE
Loading map with TSX tileset error "Missing attribute: tilecount"

### ISSUE THREAD

**Issue by Bushstar** [mattyhall/rs-tiled#265] opened 2023-05-07 07:29 UTC
Not sure if this is a bug or user error. I created a map with a compiled version of Tiled using the latest source as of the time of this issue, the map uses a TSX tilemap. When trying to load that map via `load_tmx_map` I get the following error.

`Missing attribute: tilecount`

The tileset attribute looks like the following. Note that the TMX, TSX and PNG are all in the same folder.

`<tileset firstgid="1" source="simple-isometric.tsx"/>`

The tilecount attr
[tsx_map.tar.gz](https://github.com/mapeditor/rs-tiled/files/11414206/tsx_map.tar.gz)
ibute is in the `simple-isometric.tsx`.

`<tileset version="1.10" tiledversion="1.10.1" name="simple-isometric" tilewidth="64" tileheight="64" tilecount="54" columns="6">`

If I load a map with an embedded tileset then it loads without error.

**Comment by aleokdev** [comment] 2023-05-07 07:35
Will take a look into it today.

**Comment by Bushstar** [comment] 2023-05-07 08:04
Tried to upload the files to in case it helps but GitHub does not seem to like TSX or TMX files. Sharing via gist and adding the PNG here which GitHub seems happy with. It is a simple map that I created just to test a TMX with TSX tileset.

[tsx_map.tmx](https://gist.github.com/Bushstar/41e93d84f9a0dc8919115bdaa9af8d12)
[simple-isometric.tsx](https://gist.github.com/Bushstar/6a44bc642b245644c8d92800f806f44c)
[simple-isometric.png](https://user-images.githubusercontent.com/5293433/236665340-1c8a3c17-0522-49b1-9bbb-61e9ba9cf716.png)

**Comment by aleokdev** [comment] 2023-05-07 08:45
Hmm, I can't seem to reproduce the bug. Can you send the code you're using to load it, and the version of the crate you are using?

**Comment by Bushstar** [comment] 2023-05-07 09:05
The code I'm using is linked below. The version being used is 0.11.0. The repo below is a fork of bevy_ecs_tilemap which I updated to 0.11.0. It was on 0.10.2 before but TSX maps did not work then either, thought I would update to 0.11.0 first.

Bevy has an AssetLoader, to load TMX maps via it the AssetLoader trait needs to be implemented. This trait provides a bytes to the file which I have added to BytesResourceReader which is implemented in the file below just above the lines linked. 

The code linked works with regular maps, just not TSX maps.

https://github.com/Bushstar/bevy_ecs_tilemap/blob/8dc5097fc9c3cead2471775947162a2a4050a3f5/examples/helpers/tiled.rs#L112-L114

**Comment by Bushstar** [comment] 2023-05-07 09:16
I've pushed a demo of this error to the above repo on this branch.

https://github.com/Bushstar/bevy_ecs_tilemap/tree/map_loading_error

You can run it with...

`cargo run --example 3d_iso`

**Comment by aleokdev** [comment] 2023-05-07 09:18
`Loader` calls `tiled::ResourceReader::read_from` for every dependency required in the map. I'm pretty sure that what is happening is that it's trying to load the tileset, but since you are ignoring the path given, you are giving the map byte data once again, so the `tiled` crate tries to interpret it as a tileset, and fails.

One of the goals for 0.11 was for the crate to work with bevy's loading system - However, due to lack of time on my side, I had to upload it as-is. I'm pretty sure the crate cannot work with bevy because our crate expects dependencies to be loaded secuentially without stopping, however, bevy loads files one by one.

You'll have to go the embedded way, or try to add support for it on the crate (which would be really appreciated!)

**Comment by Bushstar** [comment] 2023-05-07 09:30
Thanks for the explanation, that makes sense.

Based on this I'll take a look at updating bevy_ecs_tilemap to work with TSX maps and will create a PR if successful.

**Comment by Bushstar** [comment] 2023-05-07 10:25
Managed to get TSX maps working with the commit below. Not so happy about manually specifying the `assets` directory, `LoadContext` has an `AssetIO` which should have the path, but this is private outside of the crate. could create a `CustomAssetIo` to get around this, but this then gets more complex than it should, especially for an example. Will create a PR on bevy_ecs_tilemap and wait for feedback as it is.

https://github.com/Bushstar/bevy_ecs_tilemap/commit/a46094d2d679e85ccc908e2d1a38071f30ad74c9

**Comment by aleokdev** [comment] 2023-05-07 12:05
Neat! Ideally we should probably have support for loading dependencies separately from their parents, but that would work for now. It ain't perfect since Bevy has no idea about the deps and it won't work with other filesystems that aren't the system one, but it'll do until we update the crate to support this usecase. Thanks!

**Comment by Bushstar** [comment] 2023-05-07 12:54
I've got it, went back and checked LoadContext, it has a method to get the AssetIo so we do not need to hard code the assets directory and use the path set from Bevy.

https://github.com/Bushstar/bevy_ecs_tilemap/commit/ef9d876497cef198e78a91e09a069e1f62b3f2a2

**Comment by aleokdev** [comment] 2023-05-07 14:43
Perfect. I'll close this issue for now then. Thank you very much for opening it and bringing it to my attention :)

**Closed as not planned by aleokdev** 2023-05-07 14:43 UTC
